name: Build and upload Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  BASE_NAME: graphops/poi-radio

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.BASE_NAME }}:${{ github.event.release.tag_name }}
